export const colors = {
    FORM_BACKGROUND_COLOR: '#F9FAFF',
    TEXT_COLOR: '#A1ABC9',
    TEXT_LINK_COLOR: `#7297FF`,
    TEXT_TITLE_COLOR: `#202225`,
    INPUT_COLOR: '#FFFFFF',
    ALERT_MESSAGE_COLOR: '#F6657F',
    ACTION_BUTTON_COLOR: `#7297FF`,
};