export const colors = {
    FORM_BACKGROUND_COLOR: '#F9FAFF',
    CABINET_CONTENT_BACKGROUND_COLOR: '#F9FAFF',
    CABINET_BACKGROUND_COLOR: '#E4EBFF',
    TEXT_COLOR: '#A1ABC9',
    TEXT_LINK_COLOR: `#7297FF`,
    TEXT_TITLE_COLOR: `#202225`,
    INPUT_COLOR: '#FFFFFF',
    ALERT_MESSAGE_COLOR: '#F6657F',
    ACTION_BUTTON_COLOR: `#7297FF`,
    INACTIVE_CABINET_TAB_COLOR: '#FFFFFF',
    DISABLED_BUTTON: '#DCE0EC',
};